FROM samueljackson/crystal-plan:latest

CMD source activate                                                            \
        && pip install -e .                                                    \
        && pyinstaller -y --clean crystalplan-centos.spec                      \
        && mkdir dist/crystal-plan-centos7                                     \
        && cp docs/user_guide.pdf dist/crystal-plan-centos7                    \
        && mv dist/crystalplan dist/crystal-plan-centos7                       \
        && cd dist                                                             \
        && tar -zcvf crystal-plan-centos7.tar.gz crystal-plan-centos7
